version: '3'
services:
  web:
    container_name: my-php-app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html/

  ai:
    container_name: ai
    build:
      context: ./ai/
      dockerfile: Dockerfile
    command: flask --app app run -h 0.0.0.0 --debug
    ports:
      - "5000:5000"


