version: '3'
services:
  web:
    container_name: my-php-app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html/
    networks:
      - starter-code

  app-db:
    container_name: mysql-container
    build: ./database/
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: hive
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - starter-code


  jenkins:
    container_name: jenkins
    build:
      context: jenkins
      dockerfile: Dockerfile
    volumes:
      - jenkins-data:/var/jenkins_home
      - app:/var/www/html
    restart: always
    depends_on:
      - sonar
    environment:
      SONARQUBE_PORT: 9000
    ports:
      - '8080:8080'
    networks:
      - starter-code
#
  sonar:
    container_name: sonarqube
    image: sonarqube:latest
    restart: always
    volumes:
      - sonarqube-data:/opt/sonar-mf-cube/data
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - '9000:9000'
    networks:
      - starter-code
  ai:
    container_name: ai
    build:
      context: ./ai/
      dockerfile: Dockerfile
    command: flask --app app run -h 0.0.0.0 --debug
    ports:
      - "5000:5000"
    networks:
      - starter-code

volumes:
  app:
  jenkins-data:
  sonarqube-data:

networks:
  starter-code:


